version: '3'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    networks: 
      - local

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    ports: 
      - 5433:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: 123456
    networks: 
      - local
    tty: true

networks: 
  local:
    driver: bridge